#!/bin/sh

# IP Lists Updater для OpenWrt 24.10 с fw4
# Версия: 2.1 - Восстановлено добавление комментариев "# Source:" в итоговый файл

# --- Конфигурация ---
OUTPUT_DIR="/etc/luci-uploads"
OUTPUT_FILE="${OUTPUT_DIR}/ip_lists.txt"
TEMP_DIR="/tmp/ip_lists_temp"
LOCK_FILE="/tmp/ip_lists_updater.lock"
LOG_FILE="/var/log/ip_lists_updater.log"

# Базовые URL зеркал (каждый с новой строки для удобства)
MIRRORS="
https://raw.githubusercontent.com/Loyalsoldier/geoip/refs/heads/release/text/
https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/text/
https://fastly.jsdelivr.net/gh/Loyalsoldier/geoip@release/text/
"

# Имена файлов для загрузки (каждый с новой строки)
FILES="
cloudflare.txt
cloudfront.txt
facebook.txt
google.txt
telegram.txt
twitter.txt
fastly.txt
"

# --- Функции ---

# Функция логирования
log_message() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" | tee -a "$LOG_FILE"
}

# Функция очистки при выходе
cleanup() {
    [ -d "$TEMP_DIR" ] && rm -rf "$TEMP_DIR"
    [ -f "$LOCK_FILE" ] && rm -f "$LOCK_FILE"
}

# Проверка доступности инструментов загрузки
check_download_tool() {
    if command -v curl >/dev/null 2>&1; then
        DOWNLOAD_TOOL="curl"
    elif command -v wget >/dev/null 2>&1; then
        DOWNLOAD_TOOL="wget"
    else
        log_message "ERROR: Не найден curl или wget для загрузки файлов. Установите: opkg install curl"
        exit 1
    fi
}

# Функция загрузки файла
download_file() {
    local url="$1"
    local output_file="$2"
    
    if [ "$DOWNLOAD_TOOL" = "curl" ]; then
        curl -fsSL --connect-timeout 20 --max-time 60 --retry 2 -o "$output_file" "$url"
    else
        wget -q -T 20 -O "$output_file" "$url"
    fi
}

# Функция фильтрации IPv4 (убирает IPv6 адреса)
filter_ipv4_only() {
    local input_file="$1"
    local temp_output="${input_file}.tmp"
    
    grep '^[0-9]' "$input_file" | grep -v ':' > "$temp_output"
    mv "$temp_output" "$input_file"
}

# --- Основной скрипт ---

trap cleanup EXIT INT TERM

if [ -f "$LOCK_FILE" ]; then
    log_message "ERROR: Скрипт уже запущен. Если это не так, удалите $LOCK_FILE"
    exit 1
fi
echo $$ > "$LOCK_FILE"

log_message "INFO: Запуск обновления IP списков"
check_download_tool
mkdir -p "$OUTPUT_DIR"
mkdir -p "$TEMP_DIR"

SUCCESS_COUNT=0
TOTAL_COUNT=0

for file in $FILES; do
    TOTAL_COUNT=$((TOTAL_COUNT + 1))
    temp_file="${TEMP_DIR}/${file}"
    download_success=0
    
    log_message "--- Загрузка ${file} ---"
    
    for mirror in $MIRRORS; do
        url="${mirror}${file}"
        log_message "INFO: Попытка с зеркала: $url"
        
        if download_file "$url" "$temp_file"; then
            log_message "INFO: Успешно скачан с $mirror"
            download_success=1
            break
        else
            log_message "WARN: Неудача с зеркалом $mirror"
        fi
    done

    if [ "$download_success" -eq 1 ]; then
        if [ -s "$temp_file" ]; then
            filter_ipv4_only "$temp_file"
            
            if [ -s "$temp_file" ]; then
                SUCCESS_COUNT=$((SUCCESS_COUNT + 1))
                ipv4_count=$(wc -l < "$temp_file")
                log_message "INFO: Успешно обработан $file ($ipv4_count IPv4 адресов)"
            else
                log_message "WARN: После фильтрации IPv4 в файле $file не осталось данных"
                rm -f "$temp_file"
            fi
        else
            log_message "WARN: Файл $file пуст после скачивания"
            rm -f "$temp_file"
        fi
    else
        log_message "ERROR: Не удалось загрузить $file со всех доступных зеркал"
    fi
done

if [ $SUCCESS_COUNT -eq 0 ]; then
    log_message "ERROR: Не удалось загрузить ни одного списка. Обновление отменено."
    exit 1
fi

log_message "INFO: Успешно загружено и обработано $SUCCESS_COUNT из $TOTAL_COUNT списков"

TEMP_OUTPUT="${TEMP_DIR}/combined_ip_lists.txt"

cat > "$TEMP_OUTPUT" << EOF
# IP Lists Combined File (IPv4 Only)
# Generated: $(date '+%Y-%m-%d %H:%M:%S')
# Sources loaded: $SUCCESS_COUNT/$TOTAL_COUNT
# Auto-generated by ip-lists-downloader.sh
EOF

# ============================================================================
# ИСПРАВЛЕННЫЙ БЛОК: Объединение файлов с добавлением комментариев
# ============================================================================
log_message "INFO: Объединение списков в итоговый файл..."
for downloaded_file in "$TEMP_DIR"/*.txt; do
    # Проверяем, что это один из скачанных файлов, а не сам итоговый временный файл
    if [ -f "$downloaded_file" ] && [ "$downloaded_file" != "$TEMP_OUTPUT" ]; then
        filename=$(basename "$downloaded_file")
        echo "" >> "$TEMP_OUTPUT"
        echo "# Source: $filename" >> "$TEMP_OUTPUT"
        cat "$downloaded_file" >> "$TEMP_OUTPUT"
    fi
done

TOTAL_IPS=$(grep -c '^[0-9]' "$TEMP_OUTPUT" 2>/dev/null || echo 0)

if mv "$TEMP_OUTPUT" "$OUTPUT_FILE"; then
    log_message "INFO: Файл успешно обновлен: $OUTPUT_FILE ($TOTAL_IPS IPv4 записей)"
    chmod 644 "$OUTPUT_FILE"
    # Для автоматической перезагрузки правил firewall:
    # fw4 reload
else
    log_message "ERROR: Ошибка при обновлении файла $OUTPUT_FILE"
    exit 1
fi

log_message "INFO: Обновление завершено успешно"

if [ -f "$LOG_FILE" ] && [ $(wc -l < "$LOG_FILE") -gt 1000 ]; then
    tail -n 1000 "$LOG_FILE" > "${LOG_FILE}.tmp" && mv "${LOG_FILE}.tmp" "$LOG_FILE"
fi

exit 0
