#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# 
# 

name: AX59U_iWRT

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH for Actions'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt.git
  REPO_BRANCH: master
  #REPO_BRANCH: abd424c3e19df49bf331a5b0d0adbd71ebf14929
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: ./config/WRT.config
  DIY_P1_SH: ./sh/WRT-part1.sh
  DIY_P2_SH: ./sh/WRT-part2.sh
  #DIY_P3_SH: ./sh/WRT-part3.sh
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: false
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  UPLOAD_RELEASE: false
  TZ: Europe/Moscow

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions: 
      contents: write
      actions: write

    steps:
    - name: Free up disk space!!!
      run: |
        echo ">>> Освобождение диска"
        df -h
        sudo rm -rf /usr/share/dotnet \
                    /usr/local/lib/android \
                    /opt/ghc \
                    /opt/hostedtoolcache \
                    /opt/az \
                    /opt/microsoft \
                    "$AGENT_TOOLSDIRECTORY"
        sudo apt-get purge -y "azure*" "dotnet*" "ghc*" "llvm*" "mono*" "android*"
        sudo apt-get autoremove -y
        sudo apt-get clean
        df -h
    
    - name: Check disk space
      run: df -h

    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL https://raw.githubusercontent.com/Gzxhwq/OpenWrt-Actions/main/depends-ubuntu-2204)
        sudo -E apt-get -qq install build-essential clang flex bison g++ gawk \
        gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
        python3-setuptools rsync swig unzip zlib1g-dev file wget \
        llvm python3-pyelftools libpython3-dev aria2 jq qemu-utils ccache rename \
        libelf-dev device-tree-compiler libgmp3-dev libmpc-dev libfuse-dev
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Cloning source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone --branch $REPO_BRANCH $REPO_URL openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: Get Latest Kernel Hash
      id: get_hash
      run: |
        KERNEL_LIST=$(curl -s https://immortalwrt.kyarucloud.moe/snapshots/targets/mediatek/filogic/kmods/ | grep -oE '6\.[0-9]+\.[0-9]+-[0-9]+-[a-f0-9]+')
        echo "$KERNEL_LIST" | while read -r line; do
            version=$(echo "$line" | cut -d'-' -f1)
            major=$(echo "$version" | cut -d'.' -f1)
            minor=$(echo "$version" | cut -d'.' -f2)
            patch=$(echo "$version" | cut -d'.' -f3)
            printf "%03d%03d%03d %s\n" "$major" "$minor" "$patch" "$line"
        done | sort -r | head -n1 | cut -d' ' -f2 | cut -d'-' -f3
        LATEST_HASH=$(echo "$KERNEL_LIST" | while read -r line; do
            version=$(echo "$line" | cut -d'-' -f1)
            major=$(echo "$version" | cut -d'.' -f1)
            minor=$(echo "$version" | cut -d'.' -f2)
            patch=$(echo "$version" | cut -d'.' -f3)
            printf "%03d%03d%03d %s\n" "$major" "$minor" "$patch" "$line"
        done | sort -r | head -n1 | cut -d' ' -f2 | cut -d'-' -f3)
        echo "LATEST_HASH=${LATEST_HASH}" >> $GITHUB_ENV

    - name: Modify kernel-defaults.mk
      run: |
        cd openwrt
        sed -i "s/\$(MKHASH) md5/echo \"${LATEST_HASH}\"/g" include/kernel-defaults.mk
    - name: Debug Hash
      run: echo "Latest hash ${LATEST_HASH}"

    - name: Loading custom sources
      run: |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        chmod +x $DIY_P1_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH

    - name: update source
      run: cd openwrt && ./scripts/feeds update -a

    - name: installation source
      run: cd openwrt && ./scripts/feeds install -a

    - name: Patch Makefile
      run: |
        cd openwrt
        #sed -i '/^PKG_FIXUP:=autoreconf/d' feeds/packages/libs/libffi/Makefile
        #echo "Updated Makefile"
        #grep "PKG_FIXUP" feeds/packages/libs/libffi/Makefile || echo "String removed successfully"
        #if [ -f package/kernel/mt76/Makefile ]; then
            #echo "Modifying mt76 Makefile to skip build"
            #sed -i '1s/^/ifneq ($(CONFIG_PACKAGE_kmod-mt76),y)\nPKG_BUILD_DEPENDS:=\nendif\n/' package/kernel/mt76/Makefile
        #fi

    - name: Show config before copy
      run: |
        echo "::group::Config file before copy"
        cat openwrt/.config || echo "Config file not found"
        echo "::endgroup::"

    - name: Loading Custom Configurations
      run: |
        [ -e files ] && mv ./files openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        # Удаляем ненужные ax59u строки
        sed -i '/fdisk/d' openwrt/.config
        sed -i '/partx-utils/d' openwrt/.config
        sed -i '/fitblk/d' openwrt/.config
        sed -i '/kmod-crypto-hw-safexcel/d' openwrt/.config
        # sed -i '/mt76/d' openwrt/.config
        # Добавляем необходимые ax59u строки
        echo 'CONFIG_TARGET_mediatek=y' >> openwrt/.config
        echo 'CONFIG_TARGET_mediatek_filogic=y' >> openwrt/.config
        echo 'CONFIG_TARGET_mediatek_filogic_DEVICE_asus_rt-ax59u=y' >> openwrt/.config
        echo 'CONFIG_TARGET_ARCH_PACKAGES="aarch64_cortex-a53"' >> openwrt/.config
        #echo 'CONFIG_TARGET_ROOTFS_PARTSIZE=512' >> openwrt/.config
        # Тестовое ядро
        #echo 'CONFIG_TESTING_KERNEL=y' >> openwrt/.config
        # Нужные пакеты
        echo 'CONFIG_PACKAGE_fitblk=y' >> openwrt/.config
        echo 'CONFIG_PACKAGE_kmod-crypto-hw-safexcel=y' >> openwrt/.config
        echo 'CONFIG_PACKAGE_kmod-usb3=y' >> openwrt/.config
        #
        echo 'CONFIG_PACKAGE_kmod-mt7915e=y' >> openwrt/.config
        echo 'CONFIG_PACKAGE_kmod-mt7986-firmware=y' >> openwrt/.config
        echo 'CONFIG_PACKAGE_mt7986-wo-firmware=y' >> openwrt/.config
        echo 'CONFIG_PACKAGE_wifischedule=y' >> openwrt/.config
        echo 'CONFIG_PACKAGE_luci-app-wifischedule=y' >> openwrt/.config
        echo 'CONFIG_PACKAGE_luci-i18n-wifischedule-ru=y' >> openwrt/.config
        #
        echo 'CONFIG_PACKAGE_facinstall=y' >> openwrt/.config
        #
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH
        # Удаление mt76 из Makefile для предотвращения его сборки
        #sed -i 's/\$(SUBTARGET)\/mt76/# \$(SUBTARGET)\/mt76/' target/linux/mediatek/Makefile
        make defconfig

    - name: Show config after copy
      run: |
        echo "::group::Config file after copy"
        cat openwrt/.config || echo "Config file not found"
        echo "::endgroup::"

    - name: Fix permissions for custom files
      run: |
        cd openwrt
        echo ">>> Fixing permissions for custom uci-defaults files (zz* pattern)"
        
        # Исправляем права в files директории (пользовательские файлы)
        if [ -d "files/etc/uci-defaults" ]; then
          find files/etc/uci-defaults/ -name "zz*" -type f -exec chmod +x {} \;
          echo "Fixed permissions for zz* files in files/etc/uci-defaults/"
        fi
        
        # Исправляем права в package директории
        # find package/ -path "*/files/etc/uci-defaults/zz*" -type f -exec chmod +x {} \; 2>/dev/null || true
        
        # Исправляем права в feeds пакетах
        # find feeds/ -path "*/files/etc/uci-defaults/zz*" -type f -exec chmod +x {} \; 2>/dev/null || true
        
        echo ">>> Custom uci-defaults permissions fix completed"
        
        # Показываем результат для проверки
        echo ">>> Found custom uci-defaults files (zz* pattern):"
        find . -path "*/etc/uci-defaults/zz*" -type f -exec ls -la {} \; 2>/dev/null || echo "No custom zz* uci-defaults files found"
        
        # Показываем все файлы в uci-defaults для контроля
        echo ">>> All uci-defaults files in build:"
        find . -path "*/etc/uci-defaults/*" -type f -exec basename {} \; 2>/dev/null | sort | head -20000 || echo "No uci-defaults files found"

        # Permissions set for files in ./files/opt/
        if [ -d "./files/opt" ]; then
          find files/opt/ -name "*.sh" -type f -exec chmod 0755 {} \;
          echo "Permissions set for files in ./files/opt/"
          ls -l ./files/opt
        fi

    #- name: SSH Connection to Actions
      #uses: P3TERX/ssh2actions@v1.0.0
      #if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh != 'false') || contains(github.event.action, 'ssh')
      #env:
        #TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        #TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

    - name: Download Software Packages
      id: package
      run: |
        cd openwrt
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile Firmware
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) Thread compilation"
        echo "y" | make -j$(expr $(nproc) + 1) || echo "y" | make -j1 V=s
        echo "compile-status=success" >> $GITHUB_ENV
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
        cat $GITHUB_ENV
        echo "compile=success" >> $GITHUB_OUTPUT
        if [ -s DEVICE_NAME ]; then
          echo "device-name=$(cat DEVICE_NAME)" >> $GITHUB_OUTPUT
        fi
        echo "file-date=$(date +"%Y%m%d%H%M")" >> $GITHUB_OUTPUT

    - name: Inspection of space utilization
      if: (!cancelled())
      run: df -hT

    - name: Cleanup unnecessary build artifacts!!!
      run: |
        echo ">>> Очистка build_dir и staging_dir"
        rm -rf openwrt/build_dir openwrt/staging_dir openwrt/tmp
        df -h

    - name: Uploading the bin directory
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.compile == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: AX59U_iWRT-${{ steps.compile.outputs.device-name }}_${{ steps.compile.outputs.file-date }}
        path: openwrt/bin

    - name: Organize documents
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_ENV
        echo "organize=success" >> $GITHUB_OUTPUT

    - name: Uploading the firmware catalog
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.organize == 'success' && !cancelled()
      with:
        name: AX59U_iWRT-firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: Generate Publishing Tags
      id: tag
      if: steps.compile.outputs.compile == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "Generate Publishing Tags..."
        echo "release_tag=iWRT_AX59U" >> $GITHUB_ENV
        echo "release_tag=iWRT_AX59U" >> $GITHUB_OUTPUT
        touch release.txt
        echo "tag=success" >> $GITHUB_ENV
        echo "tag=success" >> $GITHUB_OUTPUT

    - name: Upload Firmware to Release
      uses: softprops/action-gh-release@v2
      if: steps.tag.outputs.release_tag && steps.compile.outputs.compile == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*
        prerelease: true
        draft: false

    - name: Delete the workflow run
      uses: Mattraks/delete-workflow-runs@v2.0.6
      with:
        retain_days: 4
        keep_minimum_runs: 3

    - name: Delete old version
      uses: dev-drprasad/delete-older-releases@v0.3.4
      if: steps.tag.outputs.release_tag && env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 3
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
